name: CI & Docker Build
# Add comment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.x'
            cache: 'python'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t taakujobi/python-app:latest .

      - name: Push Docker image
        run: docker push taakujobi/python-app:latest
